# Generated by Django 2.2.12 on 2020-05-28 00:00

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200527_2000'),
        ('ollas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalollapopular',
            name='message',
            field=models.TextField(db_index=True, help_text='Acá podés contar detalladamente lo que necesitás para tu olla popular, <b>cuanto mejor cuentes tu situación es más probable que te quieran ayudar</b>', max_length=2000, null=True, verbose_name='Descripción del la Olla Popular'),
        ),
        migrations.AlterField(
            model_name='historicalollapopular',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre y Apellido de el/la responsable'),
        ),
        migrations.AlterField(
            model_name='historicalollapopular',
            name='picture',
            field=models.TextField(blank=True, help_text='Si querés podés adjuntar una foto relacionada con tu olla popular, es opcional pero puede ayudar a que la gente entienda mejor tu situación', max_length=100, null=True, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='ollapopular',
            name='message',
            field=models.TextField(db_index=True, help_text='Acá podés contar detalladamente lo que necesitás para tu olla popular, <b>cuanto mejor cuentes tu situación es más probable que te quieran ayudar</b>', max_length=2000, null=True, verbose_name='Descripción del la Olla Popular'),
        ),
        migrations.AlterField(
            model_name='ollapopular',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre y Apellido de el/la responsable'),
        ),
        migrations.AlterField(
            model_name='ollapopular',
            name='picture',
            field=models.ImageField(blank=True, help_text='Si querés podés adjuntar una foto relacionada con tu olla popular, es opcional pero puede ayudar a que la gente entienda mejor tu situación', null=True, upload_to=core.utils.rename_img, verbose_name='Foto'),
        ),
        migrations.CreateModel(
            name='OllaPopularOwner',
            fields=[
                ('olla_popular', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ollas.OllaPopular')),
                ('user_iid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
        ),
    ]
