# -*- coding: utf-8 -*-
# Generated by Django 2.2.12 on 2020-05-28 02:09

import core.utils
import django.contrib.gis.db.models.fields
from django.db import migrations, models

def populate_cats(apps, schema_editor):
    Category = apps.get_model("oficios", "Category")
    Category.objects.create(name="Carpintero", code="Carpintero")
    Category.objects.create(name="Lechero", code="Lechero")
    Category.objects.create(name="Cerrajero", code="Cerrajero")
    Category.objects.create(name="Cocinero", code="Cocinero")
    Category.objects.create(name="Mecánico", code="Mecánico")
    Category.objects.create(name="Lavandero", code="Lavandero")
    Category.objects.create(name="Pescador", code="Pescador")
    Category.objects.create(name="Escultor", code="Escultor")
    Category.objects.create(name="Albañil", code="Albañil")
    Category.objects.create(name="Editor", code="Editor")


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('color', models.CharField(default='#000000', max_length=10)),
                ('icon', models.CharField(blank=True, max_length=30, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='historicaloficio',
            name='address',
            field=models.CharField(help_text='Indica la dirección, ciudad, barrio, referencias, o cómo llegar', max_length=400, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='historicaloficio',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(help_text='<p style="margin-bottom:5px;font-size:10px;">Seleccioná tu ubicación para que la gente pueda encontrarte.            <br>Si tenés problemas con este paso <a href="#" class="is-link modal-button" data-target="#myModal" aria-haspopup="true">mirá esta ayuda</a></p><p id="div_direccion" style="font-size: 10px; margin-bottom: 5px;"></p>', srid=4326, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='historicaloficio',
            name='message',
            field=models.TextField(db_index=True, help_text='Acá podés contar detalladamente en qué consiste tu oficio, <b>cuanto mejor describas tu oficio es más probable que te quieran llamar</b>', max_length=2000, null=True, verbose_name='Descripción del oficio'),
        ),
        migrations.AlterField(
            model_name='historicaloficio',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre y Apellido'),
        ),
        migrations.AlterField(
            model_name='historicaloficio',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='historicaloficio',
            name='picture',
            field=models.TextField(blank=True, help_text='Si querés podés adjuntar una foto relacionada con tu oficio, es opcional pero puede ayudar a que la gente entienda de qué se trata.', max_length=100, null=True, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='address',
            field=models.CharField(help_text='Indica la dirección, ciudad, barrio, referencias, o cómo llegar', max_length=400, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(help_text='<p style="margin-bottom:5px;font-size:10px;">Seleccioná tu ubicación para que la gente pueda encontrarte.            <br>Si tenés problemas con este paso <a href="#" class="is-link modal-button" data-target="#myModal" aria-haspopup="true">mirá esta ayuda</a></p><p id="div_direccion" style="font-size: 10px; margin-bottom: 5px;"></p>', srid=4326, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='message',
            field=models.TextField(db_index=True, help_text='Acá podés contar detalladamente en qué consiste tu oficio, <b>cuanto mejor describas tu oficio es más probable que te quieran llamar</b>', max_length=2000, null=True, verbose_name='Descripción del oficio'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre y Apellido'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='picture',
            field=models.ImageField(blank=True, help_text='Si querés podés adjuntar una foto relacionada con tu oficio, es opcional pero puede ayudar a que la gente entienda de qué se trata.', null=True, upload_to=core.utils.rename_img, verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='categories',
            field=models.ManyToManyField(blank=True, to='oficios.Category'),
        ),
        migrations.RunPython(populate_cats, migrations.RunPython.noop),
    ]
