# Generated by Django 2.2.12 on 2020-05-30 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0002_auto_20200527_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloficio',
            name='categories',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='oficios.Category'),
        ),
        migrations.RemoveField(
            model_name='oficio',
            name='categories',
        ),
        migrations.AddField(
            model_name='oficio',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oficios.Category'),
        ),
    ]
